---
deployment:
  tasks:
    - set -e
    - cd /home/familyre/repositories/family-reminder

    # Set deploy path
    - export DEPLOYPATH=/home/familyre/public_html

    # Copy all necessary files (including vendor)
    - /bin/cp -R app public system writable vendor composer.* $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH || true

    # Fix index.php path for CI4 on cPanel
    - sed -i "s|require FCPATH\s*\.\s*'\.\./app/Config/Paths.php';|require __DIR__ . '/../repositories/family-reminder/app/Config/Paths.php';|" $DEPLOYPATH/index.php

    # Optional: debug log
    - echo "Deployed successfully at $(date)"
